onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

packages:
  - 'packages/*'

catalog:
  typescript: "5.9.3"
  "@biomejs/biome": "2.4.13"
  "node-forge": "1.4.0"

overrides:
  "tmp@<0.2.6": ">=0.2.6"
  "ip-address@<10.1.1": ">=10.1.1"
  "uuid@<11.1.1": ">=11.1.1"
  "shell-quote@<1.8.4": ">=1.8.4"
  "esbuild@>=0.27.3 <0.28.1": ">=0.28.1"
  "adm-zip@<0.6.0": ">=0.6.0"
